defaultBaseImage: gcr.io/distroless/static-debian12:nonroot

builds:
  - id: centcom-satellite
    dir: .
    main: ./cmd/centcom-satellite
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Env.VERSION}}
